[package]
name = "hyper"
version = "0.1.0"
authors = ["maulana <maulanaoktofitriadi@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1.26"
pretty_env_logger = "0.3.0"
serde_json = "1.0"